# Generated by Django 3.0 on 2021-08-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=60)),
                ('market_capital', models.CharField(max_length=50)),
                ('credit_rating', models.CharField(max_length=40)),
            ],
        ),
    ]
